[package]
name = "m00lunar"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"

[dependencies.notify-rust]
version = "4.5"
default-features = false

[features]
default = ["d"]
d = ["notify-rust/d"]
z = ["notify-rust/z"]
images = ["notify-rust/images"]
